# syntax=docker/dockerfile:1
FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ENV CGO_ENABLED=0 GOOS=linux
RUN go build -o /out/app ./main.go

FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=build /out/app /app
VOLUME ["/data"]
EXPOSE 8080
USER nonroot:nonroot
ENV PORT=8080 VOLUME_PATH=/data BG_SERVICE_NAME=bg-web-svc
ENTRYPOINT ["/app"]
