- name: Install Tekton Pipelines
  shell: |
    kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml

- name: Install Tekton Triggers
  shell: |
    kubectl apply -f https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml
