- name: Add Tekton Helm repo
  shell: helm repo add cdf https://charts.cncf.dev

- name: Update Helm repos
  shell: helm repo update

- name: Install Tekton Pipelines via Helm
  shell: |
    helm upgrade --install tekton-pipeline cdf/tekton-pipeline \
      --namespace tekton-pipelines --create-namespace

- name: Install Tekton Triggers via Helm
  shell: |
    helm upgrade --install tekton-triggers cdf/tekton-triggers \
      --namespace tekton-pipelines
