
- name: Add Tekton Helm repo
  shell: helm repo add tekton https://openshift-pipelines.github.io/pipelines-helm

- name: Update Helm repos
  shell: helm repo update

- name: Install Tekton Pipelines
  shell: >
    helm install tekton-pipelines tekton/tekton-pipeline
    --namespace tekton-pipelines --create-namespace
