
- name: Add Tekton Helm repo
  shell: helm repo add cdf https://cdfoundation.github.io/tekton-helm-chart/

- name: Update Helm repos
  shell: helm repo update

- name: Install Tekton Pipelines
  shell: >
    helm install tekton cdf/tekton-pipeline \
    --namespace tekton-pipelines \
    --create-namespace \
    --kube-insecure-skip-tls-verify
  environment:
    KUBECONFIG: /root/.kube/config