- name: Add Tekton Helm repo
  shell: helm repo add cdf https://cdfoundation.github.io/tekton-helm-chart/

- name: Create kube-flannel namespace
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    verify_ssl: false
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: tekton-pipelines

- name: Tekton Pipelines
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    src: https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
    validate_certs: no