apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: tkn-build-db
  namespace: blog
spec:
  workspaces:
    - name: source
      description: This workspace will be shared throughout all steps.
  params:
    - name: image-repo
      type: string
      description: Docker image name
      default: "registry.example.com"

  tasks:
    - name: clone-repository
      taskRef:
        kind: Task
        name: git-clone
      params:
        - name: url
          value: http://git.example.com/gogs/blog.git
        - name: revision
          value: "master"
        - name: deleteExisting
          value: "true"
        - name: insecureSkipTLSVerify
          value: "true"
        - name: subdirectory
          value: ""
      workspaces:
        - name: output
          workspace: source

    - name: debug-workspace
      runAfter:
        - clone-repository
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: list-files
            image: busybox:latest
            workingDir: $(workspaces.source.path)
            script: |
              #!/bin/sh
              echo "[DEBUG] 현재 작업 디렉터리: $(pwd)"
              echo "[DEBUG] 현재 위치에서 파일 목록:"
              find / -type f -name Dockerfile.db
              #echo "[DEBUG] 전체 디렉터리 구조:"
              #ls -alR .

    - name: build-image
      runAfter:
        - debug-workspace
      taskRef:
        kind: Task
        name: buildah
      params:
        - name: IMAGE
          value: "$(params.image-repo)/blog/db:v1"
        - name: TLSVERIFY
          value: "false"
        - name: DOCKERFILE
          value: "Dockerfile.db"  # 경로는 debug 결과에 따라 조정 필요
      workspaces:
        - name: source
          workspace: source