
- name: Add Flannel Helm repo
  shell: helm repo add flannel https://flannel-io.github.io/flannel/

- name: Update Helm repos
  shell: helm repo update

- name: Ensure python3-pip is installed
  ansible.builtin.package:
    name: python3-pip
    state: present
  when: inventory_hostname in groups['controllers'] or inventory_hostname in groups['workers']
 
- name: Install kubernetes Python client library
  ansible.builtin.pip:
    name: kubernetes
    state: present
    executable: pip3
  when: inventory_hostname in groups['controllers'] or inventory_hostname in groups['workers']

- name: Create kube-flannel namespace
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    verify_ssl: false
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: kube-flannel

- name: Install Flannel (Skip TLS)
  shell: |
    helm install flannel flannel/flannel \
      --namespace kube-flannel \
      --create-namespace \
      --set podCidr="20.244.0.0/16" \
      --kube-insecure-skip-tls-verify
  args:
    creates: /etc/cni/net.d/10-flannel.conflist
  environment:
    kubeconfig: /root/.kube/config
