
- name: Add Flannel Helm repo
  shell: helm repo add flannel https://flannel-helm-charts.storage.googleapis.com
  args:
    creates: /tmp/flannel-repo-added

- name: Update Helm repos
  shell: helm repo update

- name: Install Flannel with Helm
  shell: >
    helm install flannel flannel/flannel
    --namespace kube-flannel --create-namespace
