
- name: Add Flannel Helm repo
  shell: helm repo add flannel https://flannel-io.github.io/flannel/

- name: Update Helm repos
  shell: helm repo update

- name: Create kube-flannel namespace
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    verify_ssl: false
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: kube-flannel

- name: Install Flannel (Skip TLS)
  shell: |
    helm install flannel flannel/flannel \
      --namespace kube-flannel \
      --create-namespace \
      --set podCidr="10.244.0.0/16" \
      --kube-insecure-skip-tls-verify
  args:
    creates: /etc/cni/net.d/10-flannel.conflist