apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: goblog-pipeline
spec:
  params:
    - name: repo-url
    - name: repo-revision
    - name: image-url
  workspaces:
    - name: shared-data
  tasks:
    - name: clone-source
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.repo-revision)
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: shared-data
    - name: build-image
      runAfter: [clone-source]
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: $(params.image-url)
        - name: CONTEXT
          value: $(workspaces.source.path)
        - name: TLSVERIFY
          value: "false"  # insecure registry 설정
      workspaces:
        - name: source
          workspace: shared-data
    - name: deploy-to-k8s
      runAfter: [build-image]
      taskRef:
        name: kubernetes-admin
        kind: ClusterTask
      params:
        - name: script
          value: |
            kubectl rollout restart deployment go-blog -n default
