- hosts: controllers
  become: true
  roles:
    - join_control_planes
    - install_helm
    - install_flannel
    - install_tekton

- hosts: k8s_cluster
  become: true
  roles:
    - prereqs
    - install_crio
    - install_k8s

- hosts: workers
  become: true
  roles:
    - join_workers