fullnameOverride: metallb
rbac:
  create: true
controller:
  image:
    repository: metallb/controller
    tag: v0.13.7
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
speaker:
  image:
    repository: metallb/speaker
    tag: v0.13.7
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
