- name: Add Kubernetes repo
  copy:
    src: k8s.repo
    dest: /etc/yum.repos.d/k8s.repo

- name: Install kubeadm, kubelet, kubectl
  dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: stopped

- name: Initialize cluster
  shell: |
    kubeadm init --apiserver-advertise-address=192.168.10.10 \
                 --pod-network-cidr=10.244.0.0/16 \
                 --cri-socket=unix:///var/run/crio/crio.sock
  when: inventory_hostname in groups['controller']
  register: kubeadm_init

- name: Set kubeconfig
  shell: |
    mkdir -p /root/.kube
    cp -i /etc/kubernetes/admin.conf /root/.kube/config
  when: inventory_hostname == groups['controller'][0]

- name: Copy kubeconfig to other controllers
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
  when: inventory_hostname != groups['controllers'][0]
  delegate_to: "{{ groups['controllers'][0] }}"