- name: Add Kubernetes repo
  copy:
    src: k8s.repo
    dest: /etc/yum.repos.d/k8s.repo

- name: Install kubeadm, kubelet, kubectl
  dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: stopped

- name: Initialize cluster
  shell: |
    kubeadm init --apiserver-advertise-address=192.168.10.10 \
                 --pod-network-cidr=10.244.0.0/16 \
                 --cri-socket=unix:///var/run/crio/crio.sock
  when: inventory_hostname in groups['controller']
  register: kubeadm_init

- name: Extract join command
  shell: |
    kubeadm token create --print-join-command
  register: join_cmd
  when: inventory_hostname in groups['controller']

- name: Set join command for other hosts
  set_fact:
    kubeadm_join_cmd: "{{ hostvars[groups['controller'][0]]['join_cmd']['stdout'] }}"
  when: inventory_hostname in groups['workers']

- name: Join workers to cluster
  shell: "{{ hostvars[groups['controller'][0]]['join_cmd']['stdout'] }}"
  when: inventory_hostname in groups['workers']

- name: Set kubeconfig
  shell: |
    mkdir -p /root/.kube
    cp -i /etc/kubernetes/admin.conf /root/.kube/config
