- name: Enable CRI-O repository
  copy:
    src: crio.repo
    dest: /etc/yum.repos.d/crio.repo

- name: Install CRI-O
  dnf:
    name:
      - cri-o
    state: present

- name: Enable and start crio
  systemd:
    name: crio
    enabled: true
    state: started
