
heat_template_version: 2018-08-31

description: >
  로키 및 수세 리눅스 기반으로 랩 구성. 총 두 대의 가상머신.

parameters:
  flavor:
    type: string
    default:  t1.linux-admin 
  image_opensuse:
    type: string
    default: lab-opensuse-15.6
  image_rocky:
    type: string
    default: lab-rocky-9

resources:
  lab_network:
    type: OS::Neutron::Net
    properties:
      name: lab-migration-network

  lab_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: lab-migration-subnet
      network_id: { get_resource: lab_network }
      cidr: 192.168.10.0/24
      ip_version: 4
      gateway_ip: 192.168.10.1
      enable_dhcp: true
      dns_nameservers: [8.8.8.8]

  lab_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: lab-migration
      description: Allow all traffic
      rules:
        - protocol: tcp
          direction: ingress
        - protocol: udp
          direction: ingress
        - protocol: icmp
          direction: ingress

  opensuse_port0:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: lab_network }
      fixed_ips: [{ ip_address: 192.168.10.10 }]
      security_groups: [ { get_resource: lab_sg } ]

  opensuse0:
    type: OS::Nova::Server
    properties:
      name: suse-node-1
      image: { get_param: image_opensuse }
      flavor: { get_param: flavor }
      key_name: lab-admin
      networks:
        - port: { get_resource: opensuse_port0 }
        - network: net-infra

  rocky_port0:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: lab_network }
      fixed_ips: [{ ip_address: 192.168.10.20 }]
      security_groups: [ { get_resource: lab_sg } ]

  rocky0:
    type: OS::Nova::Server
    properties:
      name: rocky-node-1
      image: { get_param: image_rocky }
      flavor: { get_param: flavor }
      key_name: lab-admin
      networks:
        - port: { get_resource: rocky_port0 }
        - network: net-infra