heat_template_version: 2018-08-31

description: lab-cicd-network 및 infra-net 기반 4개 인스턴스(controller, compute0/1, utility) 생성

parameters:
  image:
    type: string
    default: lab-rocky-9-rev3
  flavor:
    type: string
    default: v1.middle
  key_name:
    type: string
    default: lab-cicd

resources:
  lab_network:
    type: OS::Neutron::Net
    properties:
      name: lab-cicd-network

  lab_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: lab-cicd-subnet
      network_id: { get_resource: lab_network }
      cidr: 192.168.10.0/24
      gateway_ip: 192.168.10.1
      dns_nameservers: [8.8.8.8]
      enable_dhcp: true
      ip_version: 4

  lab_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name: lab-cicd
      description: Allow all TCP/UDP/ICMP
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: udp
          remote_ip_prefix: 0.0.0.0/0
        - protocol: icmp
          remote_ip_prefix: 0.0.0.0/0

  controller_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: lab_network }
      fixed_ips:
        - ip_address: 192.168.10.10
      security_groups: [ { get_resource: lab_secgroup } ]

  compute0_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: lab_network }
      fixed_ips:
        - ip_address: 192.168.10.20
      security_groups: [ { get_resource: lab_secgroup } ]

  compute1_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: lab_network }
      fixed_ips:
        - ip_address: 192.168.10.30
      security_groups: [ { get_resource: lab_secgroup } ]

  utility_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: lab_network }
      fixed_ips:
        - ip_address: 192.168.10.40
      security_groups: [ { get_resource: lab_secgroup } ]

  # infra-net 포트들
  controller_infra_port:
    type: OS::Neutron::Port
    properties:
      network: infra-net
      security_groups: [ { get_resource: lab_secgroup } ]

  compute0_infra_port:
    type: OS::Neutron::Port
    properties:
      network: infra-net
      security_groups: [ { get_resource: lab_secgroup } ]

  compute1_infra_port:
    type: OS::Neutron::Port
    properties:
      network: infra-net
      security_groups: [ { get_resource: lab_secgroup } ]

  utility_infra_port:
    type: OS::Neutron::Port
    properties:
      network: infra-net
      security_groups: [ { get_resource: lab_secgroup } ]

  controller:
    type: OS::Nova::Server
    properties:
      name: controller
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: controller_port }
        - port: { get_resource: controller_infra_port }

  compute0:
    type: OS::Nova::Server
    properties:
      name: compute0
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: compute0_port }
        - port: { get_resource: compute0_infra_port }

  compute1:
    type: OS::Nova::Server
    properties:
      name: compute1
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: compute1_port }
        - port: { get_resource: compute1_infra_port }

  utility:
    type: OS::Nova::Server
    properties:
      name: utility
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: utility_port }
        - port: { get_resource: utility_infra_port }
