heat_template_version: 2018-08-31

description: Kubernetes Cluster with 6 Rocky VMs on 3 networks (Fixed IPs on internal/external)

parameters:
  image:
    type: string
    default: lab-rocky-9-std
  flavor:
    type: string
    default: v1.middle
  key_name:
    type: string
    default: lab-k8s
  infra_net_id:
    type: string
    default: infra-net
    description: ID of the infra-net network

resources:
  sg_k8s:
    type: OS::Neutron::SecurityGroup
    properties:
      name: lab-k8s
      rules:
        - protocol: tcp
        - protocol: udp
        - protocol: icmp

  net_internal:
    type: OS::Neutron::Net
    properties:
      name: lab-k8s-internal

  subnet_internal:
    type: OS::Neutron::Subnet
    properties:
      name: subnet-k8s-internal
      network_id: { get_resource: net_internal }
      cidr: 192.168.10.0/24
      enable_dhcp: true
      gateway_ip: null
      dns_nameservers: [192.168.10.60, 8.8.8.8]

  net_external:
    type: OS::Neutron::Net
    properties:
      name: lab-k8s-external

  subnet_external:
    type: OS::Neutron::Subnet
    properties:
      name: subnet-k8s-external
      network_id: { get_resource: net_external }
      cidr: 192.168.20.0/24
      enable_dhcp: true
      gateway_ip: null
      dns_nameservers: [192.168.10.60, 8.8.8.8]

# podman
  port_podman:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: net_internal }
      fixed_ips:
        - subnet_id: { get_resource: subnet_internal }
          ip_address: 192.168.10.240
      security_groups:
        - { get_resource: sg_k8s }

  port_podman_ext:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: net_external }
      fixed_ips:
        - subnet_id: { get_resource: subnet_external }
          ip_address: 192.168.20.240
      security_groups:
        - { get_resource: sg_k8s }

  server_podman:
    type: OS::Nova::Server
    properties:
      name: podman
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: port_podman }
        - port: { get_resource: port_podman_ext }
        - network: infra-net

# haproxy
  port_proxy:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: net_internal }
      fixed_ips:
        - subnet_id: { get_resource: subnet_internal }
          ip_address: 192.168.10.250
      security_groups:
        - { get_resource: sg_k8s }

  port_proxy_ext:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: net_external }
      fixed_ips:
        - subnet_id: { get_resource: subnet_external }
          ip_address: 192.168.20.250
      security_groups:
        - { get_resource: sg_k8s }

  server_proxy:
    type: OS::Nova::Server
    properties:
      name: haproxy
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: port_proxy }
        - port: { get_resource: port_proxy_ext }
        - network: infra-net

# 노드 정의 반복: podman, proxy, control1-3, compute1-2, bootstrap

# control2
  port_control2:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: net_internal }
      fixed_ips:
        - subnet_id: { get_resource: subnet_internal }
          ip_address: 192.168.10.20
      security_groups:
        - { get_resource: sg_k8s }

  port_control2_ext:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: net_external }
      fixed_ips:
        - subnet_id: { get_resource: subnet_external }
          ip_address: 192.168.20.20
      security_groups:
        - { get_resource: sg_k8s }

  server_control2:
    type: OS::Nova::Server
    properties:
      name: control2
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: port_control2 }
        - port: { get_resource: port_control2_ext }
        - network: infra-net

# control3
  port_control3:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: net_internal }
      fixed_ips:
        - subnet_id: { get_resource: subnet_internal }
          ip_address: 192.168.10.30
      security_groups:
        - { get_resource: sg_k8s }

  port_control3_ext:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: net_external }
      fixed_ips:
        - subnet_id: { get_resource: subnet_external }
          ip_address: 192.168.20.30
      security_groups:
        - { get_resource: sg_k8s }

  server_control3:
    type: OS::Nova::Server
    properties:
      name: control3
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: port_control3 }
        - port: { get_resource: port_control3_ext }
        - network: infra-net

# compute1
  port_compute1:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: net_internal }
      fixed_ips:
        - subnet_id: { get_resource: subnet_internal }
          ip_address: 192.168.10.40
      security_groups:
        - { get_resource: sg_k8s }

  port_compute1_ext:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: net_external }
      fixed_ips:
        - subnet_id: { get_resource: subnet_external }
          ip_address: 192.168.20.40
      security_groups:
        - { get_resource: sg_k8s }

  server_compute1:
    type: OS::Nova::Server
    properties:
      name: compute1
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: port_compute1 }
        - port: { get_resource: port_compute1_ext }
        - network: infra-net

# compute2
  port_compute2:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: net_internal }
      fixed_ips:
        - subnet_id: { get_resource: subnet_internal }
          ip_address: 192.168.10.50
      security_groups:
        - { get_resource: sg_k8s }

  port_compute2_ext:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: net_external }
      fixed_ips:
        - subnet_id: { get_resource: subnet_external }
          ip_address: 192.168.20.50
      security_groups:
        - { get_resource: sg_k8s }

  server_compute2:
    type: OS::Nova::Server
    properties:
      name: compute2
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: port_compute2 }
        - port: { get_resource: port_compute2_ext }
        - network: infra-net

# bootstrap
  port_bootstrap:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: net_internal }
      fixed_ips:
        - subnet_id: { get_resource: subnet_internal }
          ip_address: 192.168.10.60
      security_groups:
        - { get_resource: sg_k8s }

  port_bootstrap_ext:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: net_external }
      fixed_ips:
        - subnet_id: { get_resource: subnet_external }
          ip_address: 192.168.20.60
      security_groups:
        - { get_resource: sg_k8s }

  server_bootstrap:
    type: OS::Nova::Server
    properties:
      name: bootstrap
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: port_bootstrap }
        - port: { get_resource: port_bootstrap_ext }
        - network: infra-net
