heat_template_version: 2018-08-31

description: Rancher cluster with 6 nodes, static IPs, SSH keypair, router setup, external access, and VNC support

parameters:
  image:
    type: string
    default: rancher-opensuse
  flavor_haproxy:
    type: string
    default: t1.rancher-haproxy
  flavor_bootstrap:
    type: string
    default: v1.large
  flavor_controller:
    type: string
    default: t1.rancher-controller
  flavor_compute:
    type: string
    default: t1.rancher-compute
  key_name:
    type: string
    default: rancher_key

resources:
  rancher_internal_net:
    type: OS::Neutron::Net
    properties:
      name: rancher-internal
      value_specs:
        mtu: 1450

  rancher_internal_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: rancher_internal_net }
      cidr: 192.168.10.0/16
      ip_version: 4
      enable_dhcp: false
      gateway_ip: null
      dns_nameservers: [192.168.10.240, 192.10.10.204, 8.8.8.8]
      allocation_pools:
        - start: 192.168.10.2
          end: 192.168.10.254

  rancher_external_net:
    type: OS::Neutron::Net
    properties:
      name: rancher-external
      value_specs:
        mtu: 1450

  rancher_external_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: rancher_external_net }
      cidr: 192.10.10.0/24
      ip_version: 4
      enable_dhcp: false
      gateway_ip: null
      allocation_pools:
        - start: 192.10.10.2
          end: 192.10.10.254

  rancher_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: rancher-sg
      rules:
        - protocol: icmp
        - protocol: tcp
          port_range_min: 1
          port_range_max: 65535
        - protocol: udp
          port_range_min: 1
          port_range_max: 65535

  node1_internal_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_internal_net }
      fixed_ips: [ { ip_address: 192.168.10.250 } ]
      security_groups: [ { get_resource: rancher_sg } ]

  node1_external_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_external_net }
      fixed_ips: [ { ip_address: 192.10.10.250 } ]
      security_groups: [ { get_resource: rancher_sg } ]

  node1_infra_port:
    type: OS::Neutron::Port
    properties:
      network: infra-net
      security_groups: [ { get_resource: rancher_sg } ]

  node1:
    type: OS::Nova::Server
    properties:
      name: haproxy
      image: { get_param: image }
      flavor: { get_param: flavor_haproxy }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: node1_internal_port }
        - port: { get_resource: node1_external_port }
        - port: { get_resource: node1_infra_port }

  node2_internal_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_internal_net }
      fixed_ips: [ { ip_address: 192.168.10.240 } ]
      security_groups: [ { get_resource: rancher_sg } ]

  node2_external_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_external_net }
      fixed_ips: [ { ip_address: 192.10.10.240 } ]
      security_groups: [ { get_resource: rancher_sg } ]

  node2_infra_port:
    type: OS::Neutron::Port
    properties:
      network: infra-net
      security_groups: [ { get_resource: rancher_sg } ]

  node2:
    type: OS::Nova::Server
    properties:
      name: bootstrap
      image: { get_param: image }
      flavor: { get_param: flavor_bootstrap }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: node2_internal_port }
        - port: { get_resource: node2_external_port }
        - port: { get_resource: node2_infra_port }

  node3_internal_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_internal_net }
      fixed_ips: [ { ip_address: 192.168.10.10 } ]
      security_groups: [ { get_resource: rancher_sg } ]

  node3_external_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_external_net }
      fixed_ips: [ { ip_address: 192.10.10.10 } ]
      security_groups: [ { get_resource: rancher_sg } ]

  node3_infra_port:
    type: OS::Neutron::Port
    properties:
      network: infra-net
      security_groups: [ { get_resource: rancher_sg } ]

  node3:
    type: OS::Nova::Server
    properties:
      name: control1
      image: { get_param: image }
      flavor: { get_param: flavor_controller }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: node3_internal_port }
        - port: { get_resource: node3_external_port }
        - port: { get_resource: node3_infra_port }

  node4_internal_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_internal_net }
      fixed_ips: [ { ip_address: 192.168.10.20 } ]
      security_groups: [ { get_resource: rancher_sg } ]

  node4_external_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_external_net }
      fixed_ips: [ { ip_address: 192.10.10.20 } ]
      security_groups: [ { get_resource: rancher_sg } ]

  node4_infra_port:
    type: OS::Neutron::Port
    properties:
      network: infra-net
      security_groups: [ { get_resource: rancher_sg } ]

  node4:
    type: OS::Nova::Server
    properties:
      name: control2
      image: { get_param: image }
      flavor: { get_param: flavor_controller }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: node4_internal_port }
        - port: { get_resource: node4_external_port }
        - port: { get_resource: node4_infra_port }

  node5_internal_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_internal_net }
      fixed_ips: [ { ip_address: 192.168.10.30 } ]
      security_groups: [ { get_resource: rancher_sg } ]

  node5_external_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_external_net }
      fixed_ips: [ { ip_address: 192.10.10.30 } ]
      security_groups: [ { get_resource: rancher_sg } ]

  node5_infra_port:
    type: OS::Neutron::Port
    properties:
      network: infra-net
      security_groups: [ { get_resource: rancher_sg } ]

  node5:
    type: OS::Nova::Server
    properties:
      name: control3
      image: { get_param: image }
      flavor: { get_param: flavor_controller }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: node5_internal_port }
        - port: { get_resource: node5_external_port }
        - port: { get_resource: node5_infra_port }

  node6_internal_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_internal_net }
      fixed_ips: [ { ip_address: 192.168.10.40 } ]
      security_groups: [ { get_resource: rancher_sg } ]

  node6_external_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_external_net }
      fixed_ips: [ { ip_address: 192.10.10.40 } ]
      security_groups: [ { get_resource: rancher_sg } ]

  node6_infra_port:
    type: OS::Neutron::Port
    properties:
      network: infra-net
      security_groups: [ { get_resource: rancher_sg } ]

  node6:
    type: OS::Nova::Server
    properties:
      name: compute1
      image: { get_param: image }
      flavor: { get_param: flavor_compute }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: node6_internal_port }
        - port: { get_resource: node6_external_port }
        - port: { get_resource: node6_infra_port }

  client_internal_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_internal_net }
      fixed_ips: [ { ip_address: 192.168.10.241 } ]
      security_groups: [ { get_resource: rancher_sg } ]

  client_external_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_external_net }
      security_groups: [ { get_resource: rancher_sg } ]

  client_infra_port:
    type: OS::Neutron::Port
    properties:
      network: infra-net
      security_groups: [ { get_resource: rancher_sg } ]

  client:
    type: OS::Nova::Server
    properties:
      name: rancher-client
      image: { get_param: image }
      flavor: v1.middle
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: client_external_port }
        - port: { get_resource: client_infra_port }

  reserved_port_251:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_external_net }
      fixed_ips:
        - ip_address: 192.10.10.251
      security_groups: [ { get_resource: rancher_sg } ]

  reserved_port_252:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_external_net }
      fixed_ips:
        - ip_address: 192.10.10.252
      security_groups: [ { get_resource: rancher_sg } ]

  reserved_port_253:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_external_net }
      fixed_ips:
        - ip_address: 192.10.10.253
      security_groups: [ { get_resource: rancher_sg } ]

  reserved_port_254:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: rancher_external_net }
      fixed_ips:
        - ip_address: 192.10.10.254
      security_groups: [ { get_resource: rancher_sg } ]
