apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-busybox
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: vpa-busybox.yaml
  updatePolicy:
    updateMode: "Auto"
