apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: user1-namespace
  name: user1-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
