- name: Install required packages
  dnf:
    name:
      - curl
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - bash-completion
      - iproute
    state: present

- name: Enable br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Set sysctl for k8s networking
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward = 1

- name: Apply sysctl settings
  command: sysctl --system
