---
- name: Create local user with prompted password (sha512_crypt)
  hosts: all
  become: true

  # 슬라이드1: vars_prompt (encrypt, confirm, salt_size, private, unsafe)
  vars_prompt:
    - name: uusername
      prompt: "Enter username to create"
      private: no
    - name: assigned_role
      prompt: "Is this an admin user? (yes/no)"
      private: no

    - name: upassword
      prompt: "Enter new password"
      private: yes
      confirm: yes
      encrypt: sha512_crypt
      salt_size: 10
      unsafe: yes
  tasks:
    - name: "Creating user {{ uusername }} without admin access"
      user:
        name: "{{ uusername }}"
        password: "{{ upassword }}"
        state: present
        create_home: true
      when: assigned_role | lower == "no"
    - name: "Creating admin user {{ uusername }} (wheel/sudo)"
      user:
        name: "{{ uusername }}"
        password: "{{ upassword }}"
        state: present
        create_home: true
        groups: "{{ 'wheel' if ansible_facts['os_family']=='RedHat' else 'sudo' }}"
        append: true
      when: assigned_role | lower == "yes"
# ansible-playbook -i inventory create-user-with-password.yaml