# vi nm_configure.yaml
 - name: nmcil ipv4 Addr, ipv4 GW and ipv4 DNS
   nmcli:
     type: ethernet
     conn_name: '{{ item.conn_name }}'
     ip4: '{{ item.ip4 }}'
     gw4: '{{ item.gw4 }}'
     dns4: '{{ item.dns }}'
     state: present
   with_items:
     - '{{ nmcli_ethernet }}'