cat <<EOF> cluster-init-config.yaml
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
nodeRegistration:
  name: "control1.example.com"
localAPIEndpoint:
  advertiseAddress: "192.168.10.10"
  bindPort: 6443
bootstrapTokens:
  - token: "abcdef.0123456789abcdef"
    ttl: "24h0m0s"
    description: "bootstrap token"
    usages:
      - authentication
      - signing
    groups:
      - system:bootstrappers:kubeadm:default-node-token
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: v1.32.8
networking:
  podSubnet: "10.88.0.0/16"
  serviceSubnet: "11.96.0.0/12"
  dnsDomain: "cluster.local"
controlPlaneEndpoint: "192.168.10.50:6443"
EOF