apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: node1.example.com
  - matchLabels:
      kubernetes.io/hostname: node2.example.com
ipAddressPools:
  - lb-test-ip-pool
  interfaces:
  - ens7
