- name: Generate kubeadm join command on primary controller
  command: kubeadm token create --print-join-command
  become: yes
  run_once: true
  delegate_to: "{{ groups['controllers'][0] }}"
  register: join_cmd

- name: Join worker nodes to the cluster
  command: "{{ join_cmd.stdout }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
  become: yes
  when: inventory_hostname in groups['workers']